project:
  type: website
  output-dir: docs

website:
  title: "Language Acquisition"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Syllabus
      - href: schedule.md
        text: Schedule
      - href: assignments.qmd
        text: Requirements
      - href: readings.qmd
      - href: policies.qmd
        text: "Policies"
      - href: resources.qmd

format:
  html:
    theme: journal
    toc: true
    css: styles.css