project:
  type: website
  output-dir: docs

website:
  title: "Language Acquisition"
  sidebar:
    style: docked
    search: true
    contents:
      - href: syllabus.md
        text: Syllabus
      - href: schedule.md
      - href: assignments.qmd
      - href: policies.qmd
        text: "Course Policies"
      - href: resources.qmd

format:
  html:
    theme: journal
    toc: true