---
title: "LING-5151: Language Acquisition, Spring 2026"
---

# Basic Information

| | | 
| --- | --- |
| **Professor** | Heidi Getz, Ph.D. [heidi.getz@georgetown.edu](mailto:heidi.getz@georgetown.edu) <br> Poulton Hall 223 (Linguistics), Building D, Room 154 (Neurology)  | 
| **Class schedule** | Thursdays 9:30-12pm, Car Barn 172  | 
| **Office hours** | By appointment: [https://calendly.com/hrg2/officehours](https://calendly.com/hrg2/officehours)    | 
| **Prerequisites** | Prior coursework in linguistics, psychology, or cognitive science; or permission of instructor.   | 


# Course description

This is an interdisciplinary course on child language acquisition designed to introduce students to what is known about the cognitive and neural processes underlying children’s acquisition of language, as well as the scientific process through which this knowledge was constructed. We will cover universals of language acquisition across languages and modalities (signed and spoken); similarities and differences between child and adult language learners; psychological and linguistic theories of the learning process; and the influential (and controversial) idea that humans are born with innate knowledge of language (a “Universal Grammar”). We will explore a range of perspectives on these issues by reading and discussing research papers from psychology, linguistics, neuroscience, and cognitive science. To allow students to engage with all of these perspectives, the course will provide background on relevant research methodologies (e.g. experiments testing infants’ or children’s linguistic knowledge; artificial language learning; brain imaging) as well as practical training on how to read and understand scientific papers in an unfamiliar field. 

# Learning goals

The course is designed to achieve the following learning outcomes:

* Knowledge of the basic principles, important theoretical issues, and foundational empirical evidence in the field of child language acquisition  
* Understanding of the scientific process through which such knowledge is constructed   
* The ability to interpret linguistic, psychological, and neurobiological evidence relevant to language acquisition  
* The ability to engage critically and constructively with scientific ideas and evidence  
* An understanding of how research in language acquisition relates to broader societal issues

# Structure

Most classes will be a mix of lecture, discussion, and student presentations. The first half of class will usually include student presentations and group discussion. The second half will include a lecture that provides background and context for the readings you will do for the following class.

Each week, there will be a short or medium-size written assignment as well as assigned readings. The written assignments are all due on Mondays at 11:59pm. The assigned readings should be completed before class on Thursday.


# Topics & Bibliography

See [schedule](schedule.md).

**Topics in Language Acquisition**

1. Universal acquisition milestones across modalities (speech and sign), sensory experiences (deaf, blind, sighted/hearing) and cultures ([WEIRD](https://en.wikipedia.org/wiki/Psychology#WEIRD_bias) and not)  
2. Learning mechanisms (distributional/statistical learning, rule learning, hypothesis-testing, bootstrapping)  
3. Environmental and biological factors (critical periods, home sign, the controversial “30 million word gap”, development of language in the brain)

**Scientific Literacy**

In addition to the main course content, we will cover the following:

* How to read an scientific paper  
* How to present a scientific paper  
* How to summarize a scientific paper  
* The structure of a literature review  
* Identifying and locating scientific sources (types of scientific papers, using Google Scholar, accessing pdfs)  
* Understanding journal names  
* Using reference managers  
* My note-taking system  
* Authorship conventions  
* PNAS article types  
* Databases of marginalized scholars   
* Impact factors

