# Course policies

## **Names**

You can call me by my first name (Heidi) or, if you’re more comfortable using a title, Professor Getz or Dr. Getz. 

To help me learn your name, please consider using [this link](https://www.speakpipe.com/HeidiGetz) to record yourself saying your name the way you’d like me to pronounce it.

## **Attendance**

I will not take formal attendance. However, I do expect you to be consistently present. Repeated unexplained absences will affect your grade. If you know in advance that you won’t be able to make it to a particular class due to a religious holiday, sports conflict, etc., no problem—just let me know ahead of time.

If you’re sick and/or contagious, please DO NOT come to class. Email me to let me know you are not well enough to come. I will not ask any follow-up questions, and I will never require you to provide a doctor’s note.

This class is held in-person. There is no Zoom option.

## **Informal auditors**

PhD students, postdocs, and visiting researchers are welcome to attend this course without formally enrolling ("audit"). I may ask informal auditors to present one of the readings, depending on how many students are formally enrolled. Other than this, informal auditors are not required to complete any of the course assignments. However, I do expect informal auditors to attend class consistently; to prepare for class by doing the readings in advance; and to be engaged and attentive throughout class. Please do not work on anything else during class. Auditors who do not give the class their full attention may be asked to stop attending.

## **Extensions**

For written assignments that are part of the course project (your literature review), you may request an extension of up to one week. You don’t have to tell me why. You can request an extension for as many assignments as you need to, but you can’t request more than one extension per assignment.

Extensions will NOT be granted for the presentations or for the take-home assessments. 

## **Use of AI**

I think that generative AI (Chat GPT, etc.) can be a great tool and that students should learn to use it. However, this course is not the place for you to do that. This course is also not one in which generative AI would do a particularly good job. In any case, I expect you to complete all of your work without the aid of generative AI, unless I specifically say otherwise. In this course, **presenting AI-generated work (including text and ideas) as your own constitutes a violation of academic integrity**. If I suspect that AI was used for an assignment, I will refer the submission to the Honor Council for investigation. This can have enormous consequences for you, including a permanent notation on your transcript or even suspension or dismissal from Georgetown.

It is ok to use basic copy-editing/spell-checking tools like the ones provided by Grammarly, Microsoft Word, and Google Docs.

## **Course Materials**

The materials used in Georgetown University courses ("Course Materials") generally represent the intellectual property of course instructors which may not be disseminated or reproduced in any form for public distribution (e.g., sale, exchange, etc.) without the written permission of the course instructor. Course Materials include all written or electronic documents and materials, including syllabi, current and past examination questions/answers, and presentations such as lectures, videos, PowerPoints, etc., provided by a course instructor. Course Materials may only be used by students enrolled in the course for academic (course-related) purposes. 

## **Accommodations**

If you might require an accommodation in this course, you may contact the [Academic Resource Center (ARC)](https://academicsupport.georgetown.edu/). Available accommodations include notetaking assistance, interpreting/CART services, extra time on assignments, or any other accommodation that the ARC deems “reasonable” based on a conversation with you and documentation from the appropriate people (e.g. your doctor). To arrange accommodations (or just to explore this option), email [arc@georgetown.edu](mailto:arc@georgetown.edu) or visit the ARC in-person (Leavey Center, Suite 335, which is accessible from the elevators next to the student credit union, around the corner from the bookstore). There’s more information about this process on [the ARC’s website](https://academicsupport.georgetown.edu/disability/).

## **Religious holidays**

Georgetown University promotes respect for all religions. Any student who is unable to attend classes or to participate in any examination, presentation, or assignment on a given day because of the observance of a major religious holiday or related travel shall be excused and provided with the opportunity to make up, without unreasonable burden, any work that has been missed for this reason and shall not in any other way be penalized for the absence or rescheduled work. Students will remain responsible for all assigned work. Students should notify professors in writing at the beginning of the semester of religious observances that conflict with their classes. The Office of the Provost, in consultation with Campus Ministry and the Registrar, will publish, before classes begin for a given term, a list of major religious holidays likely to affect Georgetown students. This list can be found on the Campus Ministry website, [http://campusministry.georgetown.edu](http://campusministry.georgetown.edu/). The Provost and the Main Campus Executive Faculty encourage faculty to accommodate students whose bona fide religious observances in other ways impede normal participation in a course. Students who cannot be accommodated should discuss the matter with an advising dean.

