---
title: "Resources"
---

## **Learning Resources**
For this course, an important resource is [my guide to reading scientific papers](https://hrgetz.github.io/guide.html). Feel free to share this with anyone you like, now and in the future.

Georgetown offers a host of [learning resources](http://scs.georgetown.edu/academic-affairs/resources/) to its students. Two that you might find particularly helpful in this course are the [Writing Center](https://writingcenter.georgetown.edu/) and [Refworks](http://guides.library.georgetown.edu/refworks).

* [The Writing Center](https://writingcenter.georgetown.edu/) offers peer tutoring by trained graduate and undergraduate students who can assist you at any point in the writing process. They help at any stage of your writing process, from brainstorming to revision. Tutors can offer advice on thesis development, use of evidence, organization, flow, sentence structure, grammar, and more. The Writing Center will not proofread or edit papers; rather, they will help to improve your proofreading and editing skills to become a better writer. Appointments can be booked online through their website.
* [Refworks](http://guides.library.georgetown.edu/refworks) is an online research management tool that aids in organizing, storing, and presenting citation sources for papers and projects. (In this course we will also talk about other ways of managing references and research notes.)


## **Sexual Misconduct**

I am committed to supporting survivors of sexual misconduct, including relationship violence, sexual harassment, and sexual assault. **However, university policy also requires me to report any disclosures about sexual misconduct to the Title IX Coordinator, whose role is to coordinate the University’s response to sexual misconduct.** If I report an incident to the Title IX Coordinator, the coordinator would then reach out to you to provide support, resources, and the option to meet. You would not be required to meet with the coordinator. More information about reporting options and resources is available [here](https://sexualassault.georgetown.edu/#_ga=2.84763163.302405512.1597672771-114879328.1580830596).

As an alternative to speaking with me or another mandated reporter, you can reach out for support and assistance to these other fully confidential professional resources:

* Confidential email address for Sexual Assault Response and Prevention (SARP): [sarp@georgetown.edu](mailto:sarp@georgetown.edu)  
* Jen Schweer, MA, LPC, Associate Director of Health Education Services for Sexual Assault Response and Prevention (202) 687-0323 | [jls242@georgetown.edu](mailto:jls242@georgetown.edu)  
* Brittany Egan, MSW, LICSW, CCTP, Staff Clinician and Sexual Assault Services Specialist, Health Education Services (202) 687-0323 | [be200@georgetown.edu](mailto:be200@georgetown.edu)  
* Counseling and Psychiatric Services (CAPS), (202) 687-6985

## **Office of the Student Ombuds (OSO)**

Confidential | Independent | Impartial | Informal

The Office of the Student Ombuds (OSO) serves all undergraduate and graduate students, including SCS and BGE, on the main campus. Consider contacting the Student Ombuds when you want to talk to a caring professional about a University-related issue but don't know where to turn. The OSO is a confidential and safe space that is independent of formal university organizations or structures where students can discuss their concerns, share their experiences, ask questions and explore their options. The student ombuds can help you problem-solve, identify your goals, and empower you to think through ways to navigate complex situations. Some reasons for you to visit the office may be to address academic concerns, clarify administrative policies, discuss interpersonal conflicts, seek coaching, mediation or facilitation to handle a sensitive situation, advise you on the process to file a formal complaint if you are experiencing bias, harassment, bullying or other forms of intimidation, identify other appropriate campus resources, and allow you to safely express your frustrations and concerns.

Request an in-person or zoom appointment with the Student Ombuds by writing studentombuds@georgetown.edu  or calling 202-784-1081. The OSO is located in Room 207 of the Reiss Building (across from Arrupe Hall). Find more information at [http://studentombuds.georgetown.edu](http://studentombuds.georgetown.edu/).

